### ISSUE TITLE
Hangman Game Review 

### ISSUE THREAD

**Issue by ceciliawambui** [MohammedRaghib/Week-2-Project-Python#1]
### Areas Well Done
- The game is well done!
- The code is well-structured and divided into logical sections, making it easy to read and understand. The use of functions like hangman() adds clarity and promotes reusability.
- The game provides clear feedback on the number of incorrect guesses left, the guessed letters, and whether the guessed letter is correct.

### Areas of Improvements
- Add a feature to allow the player to restart the game after it ends, rather than terminating the script.

**Comment by MohammedRaghib** [comment]
Added the feature to play again, after winning or losing.

**Comment by ceciliawambui** [comment]
Great!
